### ISSUE TITLE
Can you clarify? 

### ISSUE THREAD

**Issue by AIMusicExperiment** [Fannovel16/ComfyUI-Loopchain#2]
I build custom workflow graphs for comfyui. As such your loopchain nodes are very attractive to me. I also use much of MEL's nodes. I can tell from you attributions in the code that this is somewhat of a derivative work.  Between the two I am very close to having what I need, but I'm not quite there.  I have played with your sample workflow and if I just do what you say to do, it does what you say it will do. But it leaves me dazed and confused. 

I don't really "get" the key thing. If i try to reference a file folder I get the JavaScript emoji telling me that I'm stupid. Is there a way that I can have your node load frames from a specific folder, process them in the workflow and save them in another specified folder? The way your sample flow is set up, I can't even find the output frames in the comfy directory structure. 

Where I really see potential for your system is using the loopchain sequence thingy. To that end I wonder if you could modify Mel's animation builder to accept a loopchain input, and do a pull request? That would make my life so much happier.  

I'm aware that this is a sort of side project for you as you remain busy with the controlnet stuff, but If you could take a little time to perfect this, I will be eternally in your debt.

**Comment by Fannovel16** [comment]
> I don't really "get" the key thing. If i try to reference a file folder I get the JavaScript emoji telling me that I'm stupid.

The key is the name of the storage. If you use `FolderToImageStorage` with key `foo` for example, you have to type key `foo` in `ImageStorageExportLoop` to get images. Don't use Primitive nodes as it will link a node from one chain to another, merging them into a single one.

> The way your sample flow is set up, I can't even find the output frames in the comfy directory structure.

I forgot to place a `SaveImage` node 😅. The output of ImageStorageExportLoop is images so you can link it to any node accepting `IMAGE`

> To that end I wonder if you could modify Mel's animation builder to accept a loopchain input, and do a pull request?

I can but idk if Mel would accept it. While it is true that Loopchain is kinda a derivative work, the code behind it is actually much more hacky. ComfyUI's workflow execution is linearity which means all unrelated nodes have to be programatically muted when Loopchain is executed (that is the reason you always see a very fast flashing effect on the screen).

**Comment by Fannovel16** [comment]
Also, I'll try to hide the `key` thing as it seems to worsen the UX.

**Comment by michail935** [comment]
Hi.I have a question.I downloaded "Loopchain",before that I installed ComfyUI-Frame-Interpolation.And ComfyUI-Frame-Interpolation works. For the test, I downloaded images from the page "Fannovel16
/ComfyUI-Loopchain" page and placed them in "ComfyUI_windows_portable\ComfyUI\input\heads". Also downloaded the workflow.I enter my SD model, my Canny, but nothing happens. I get an error. There are nodes in the workflow that are not connected, how do I connect them? Or should they stay as they are? I tried to find some information about how to work with this extension, but nobody knows. I am not a programmer, I do video processing and animation generation/AnimateDiff/Deforum. Could you explain or describe how to make the "Loopchain" extension work? 
Perhaps there is some description, or better video tutorial how to use the extension? Also read up on Civitay. There is one single image with small "Loup nodes", but I don't have them. I tried to find them, there are none. I hope for your answer. But of course it is better to visually see how it should be done, because not all programmers.

It's giving me this error:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\ai\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ai\comfy\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Loopchain\nodes\storages.py", line 59, in execute
    assert GLOBAL_IMAGE_STORAGE[key], f"Image storage {key} doesn't exist."
           ~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'test_canny'
